// apps/web/src/app/game/play/[roomId]/components/GameCell.tsx
'use client';

import { motion } from 'framer-motion';
import React from 'react';
import { Cell } from '../../../../types/types';
import { useGameContext } from '../../../context/game-context';

interface GameCellProps {
  cell: Cell;
  isSelected: boolean;
  onSelectStart: (position: [number, number]) => void;
  onSelectEnd: () => void;
  onSelectEnter: (position: [number, number]) => void;
}

export default function GameCell({ cell, isSelected, onSelectStart, onSelectEnd, onSelectEnter }: GameCellProps) {
  const { state } = useGameContext();
  const player = state.players.find((p) => p.id === cell.foundBy);

  const backgroundStyle = isSelected
    ? { backgroundColor: '#bfdbfe' }
    : player
      ? { backgroundColor: player.color }
      : { backgroundColor: '#ffffff' };

  return (
    <motion.div
      className="flex items-center justify-center border border-gray-300 rounded cursor-pointer select-none relative"
      onMouseDown={() => onSelectStart([cell.x, cell.y])}
      onMouseUp={onSelectEnd}
      onMouseEnter={() => onSelectEnter([cell.x, cell.y])}
      onTouchStart={() => onSelectStart([cell.x, cell.y])}
      onTouchEnd={onSelectEnd}
      whileHover={{ scale: 1.05 }}
      transition={{ duration: 0.1 }}
      style={{ minHeight: '40px', minWidth: '40px', ...backgroundStyle }}
    >
      <span className="text-lg font-bold">{cell.letter}</span>
    </motion.div>
  );
}

// apps/web/src/app/game/play/components/game-cell.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as types from '../../types/types';

@Component({
  selector: 'app-game-cell',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      class="flex items-center justify-center border border-gray-300 rounded cursor-pointer select-none relative"
      (mousedown)="onSelectStart()"
      (mouseup)="onSelectEnd()"
      (mouseenter)="onSelectEnter()"
      (touchstart)="onSelectStart()"
      (touchend)="onSelectEnd()"
      [ngStyle]="backgroundStyle"
    >
      <span class="text-lg font-bold">{{ cell.letter }}</span>
    </div>
  `,
})
export class GameCellComponent {
  @Input() cell!: types.Cell;
  @Input() isSelected: boolean = false;
  @Output() selectStart = new EventEmitter<[number, number]>();
  @Output() selectEnter = new EventEmitter<[number, number]>();
  @Output() selectEnd = new EventEmitter<void>();

  get backgroundStyle(): { [key: string]: string } {
    if (this.isSelected) {
      return { backgroundColor: '#bfdbfe' };
    } else if (this.cell.foundBy) {
      return { backgroundColor: '#a0aec0' };
    }
    return { backgroundColor: '#ffffff' };
  }

  onSelectStart(): void {
    this.selectStart.emit([this.cell.x, this.cell.y]);
  }
  onSelectEnter(): void {
    this.selectEnter.emit([this.cell.x, this.cell.y]);
  }
  onSelectEnd(): void {
    this.selectEnd.emit();
  }
}
